/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lire son propre compte
         * @description Rend le compte porté par le jeton, et lui seul : la route ne prend aucun identifiant. C'est d'ici que le site et l'app tirent l'adresse et le pilote choisi comme avatar du compte connecté, `POST /session` ne rendant qu'un jeton. Ni empreinte du mot de passe, ni dates, ni suspension.
         */
        get: operations["readOwnAccount"];
        put?: never;
        /**
         * Inscrire un compte
         * @description Crée un compte à partir d'une adresse e-mail, d'un mot de passe assez robuste et d'une preuve anti-robot (`GET /account/human-challenge`). Route publique.
         */
        post: operations["registerAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/human-challenge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtenir un défi anti-robot
         * @description Rend un défi à résoudre avant `POST /account` (SPEC-007). Route publique.
         */
        get: operations["issueHumanChallenge"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Changer son mot de passe
         * @description Change le mot de passe du compte porté par le jeton. Le mot de passe actuel est exigé.
         */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/password-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Demander un lien de réinitialisation du mot de passe
         * @description Route publique. Si un compte actif porte cette adresse, un lien valable une heure et une seule fois lui est envoyé par e-mail ; l'api n'en garde que l'empreinte SHA-256. La réponse est la même que l'adresse ait un compte ou non. Une seconde demande pour le même compte moins de deux minutes après la précédente n'envoie rien de plus.
         */
        post: operations["requestPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/password-reset/confirmation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Choisir un nouveau mot de passe avec le lien reçu
         * @description Route publique. Le jeton est celui du lien reçu par e-mail (`/mot-de-passe/nouveau?jeton=…`). Une réinitialisation réussie dépense tous les liens encore valables du compte. Les sessions déjà ouvertes restent valables, comme après un changement de mot de passe.
         */
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ouvrir une session
         * @description Vérifie les identifiants et rend un jeton d'accès.
         *
         *     Les essais infructueux sont ralentis : le délai dépend du couple (compte, origine IP) et croît avec les échecs récents. Une origine que la requête ne nomme pas retombe sur une clé commune. Le ralentissement n'a pas de code de statut propre — un essai ralenti répond simplement plus tard, toujours `401` s'il échoue, pour ne pas distinguer une adresse inconnue d'un mot de passe faux.
         */
        post: operations["signIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/listing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lister les annonces actives
         * @description Rend toutes les annonces actives. Route publique, sans pagination ni filtre à ce jour.
         */
        get: operations["listListings"];
        put?: never;
        /**
         * Publier une annonce
         * @description Publie une annonce pour une place — identifiée par le couple (adresse, box) — au nom du compte porté par le jeton.
         *
         *     La grille tarifaire doit être complète au sens du domaine : au moins un palier, et pas de palier contradictoire.
         */
        post: operations["publishListing"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/listing/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lister ses propres annonces
         * @description Rend les annonces du compte appelant, **quel que soit leur statut** — c'est la seule route qui montre une annonce dépubliée. Déclarée avant `/listing/{id}` côté serveur, sans quoi « mine » serait décodé comme un identifiant.
         */
        get: operations["listOwnerListings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/listing/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Identifiant de l'annonce (UUID), tel que rendu par `GET /listing`.
                 * @example 3f1a9c0e-9c1e-4c5e-8a2b-1f2d3e4a5b6c
                 */
                id: components["parameters"]["ListingId"];
            };
            cookie?: never;
        };
        /**
         * Lire une annonce
         * @description Rend une annonce par son identifiant. Route publique : une annonce est lisible par tout le monde.
         *
         *     Un identifiant mal formé répond `404`, comme un identifiant inconnu.
         */
        get: operations["getListing"];
        put?: never;
        post?: never;
        /**
         * Dépublier une annonce
         * @description Dépublie l'annonce du compte porté par le jeton.
         *
         *     L'opération est idempotente : un identifiant mal formé, inconnu, ou une annonce déjà dépubliée répondent tous `204`. Cette route n'est donc pas un oracle d'existence.
         */
        delete: operations["unpublishListing"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/listing/{id}/pricing": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Identifiant de l'annonce (UUID), tel que rendu par `GET /listing`.
                 * @example 3f1a9c0e-9c1e-4c5e-8a2b-1f2d3e4a5b6c
                 */
                id: components["parameters"]["ListingId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Changer la grille tarifaire d'une annonce
         * @description Remplace la grille tarifaire de l'annonce active. Un palier absent du corps est effacé : la grille envoyée remplace la précédente en entier.
         */
        patch: operations["updateListingPricing"];
        trace?: never;
    };
    "/rental-request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lister les demandes que l'on a faites
         * @description Rend les demandes de location faites par le compte appelant, en tant que locataire.
         */
        get: operations["listMyRentalRequests"];
        put?: never;
        /**
         * Demander une location
         * @description Demande la location d'une place — identifiée par le couple (adresse, box) — sur une période de jours calendaires, au nom du compte porté par le jeton, et ouvre la page de paiement Stripe au prix que l'api a figé.
         *
         *     La demande reste en attente de paiement jusqu'à ce que Stripe annonce l'empreinte ; le délai de `RENTAL_REQUEST_EXPIRY_IN_HOURS` (48 heures par défaut) court ensuite depuis l'empreinte. Une page de paiement vaut trente minutes.
         */
        post: operations["requestRental"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rental-request/received": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lister les demandes reçues sur ses places
         * @description Rend les demandes faites sur les annonces du compte appelant, en tant que propriétaire. C'est **la seule route qui rend l'identifiant d'une demande** à un client, et donc la seule qui rende `POST /rental-request/{id}/confirmation` atteignable.
         */
        get: operations["listReceivedRentalRequests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rental-request/{id}/confirmation": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Identifiant de la demande de location (UUID).
                 * @example 9b2f4d6a-1c3e-4f5a-8b7c-0d1e2f3a4b5c
                 */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirmer une demande de location
         * @description Confirme une demande de location. Seul le propriétaire de la place peut confirmer.
         *
         *     Un identifiant mal formé, une demande inconnue et une demande appartenant à quelqu'un d'autre répondent toutes `404`, avec le même message.
         *
         *     Confirmer prélève l'empreinte du conducteur. Si sa banque refuse le prélèvement, la confirmation répond `409` et la demande passe en `PAYMENT_FAILED`.
         */
        post: operations["confirmRentalRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/access": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Savoir si ce compte administre le site
         * @description Ne rend aucun corps : le code suffit. Le site public s'en sert pour decider s'il offre ses onglets d'administration. L'appartenance est relue en base a chaque appel, jamais portee par le jeton, pour qu'une revocation prenne effet immediatement.
         */
        get: operations["confirmAdminAccess"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lire le tableau de bord d'administration
         * @description Cumuls, activité des dernières 24 h et 7 jours, et ce qui demande une attention.
         */
        get: operations["readAdminOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lister tous les comptes
         * @description Avec leur date d'inscription, leur éventuelle suspension et leur activité.
         */
        get: operations["listAdminAccounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/listings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lister toutes les annonces
         * @description Y compris dépubliées, avec l'adresse e-mail de leur propriétaire.
         */
        get: operations["listAdminListings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/rental-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lister toutes les demandes de location
         * @description Tous statuts confondus, avec le propriétaire et le locataire.
         */
        get: operations["listAdminRentalRequests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/listings/{id}/unpublish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dépublier l'annonce de quelqu'un d'autre
         * @description Le propriétaire n'en est pas averti par le produit : il le découvre sur son tableau de bord.
         */
        post: operations["adminUnpublishListing"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/accounts/{id}/suspension": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Suspendre un compte
         * @description La suspension **bloque la connexion** : `POST /session` répond alors 401, du même refus qu'une adresse inconnue — répondre différemment apprendrait qu'une adresse existe et qu'elle est sanctionnée. Les annonces et locations en cours ne sont pas touchées.
         */
        post: operations["adminSuspendAccount"];
        /**
         * Lever la suspension d'un compte
         * @description Exige un motif comme la suspension : lever une sanction est une décision autant que la prononcer.
         */
        delete: operations["adminLiftAccountSuspension"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/rental-requests/{id}/cancellation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Annuler une demande de location
         * @description Confirmée ou non. **Aucun remboursement n'est émis** : le produit ne sait pas encaisser, donc il ne sait pas rendre. La place redevient libre — la contrainte d'exclusion ignore les demandes annulées.
         */
        post: operations["adminCancelRentalRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rental-request/{id}/abandonment": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Identifiant de la demande de location (UUID).
                 * @example 9b2f4d6a-1c3e-4f5a-8b7c-0d1e2f3a4b5c
                 */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Abandonner sa demande avant de payer
         * @description Appelée quand le conducteur revient de Stripe sans payer : la page de paiement est fermée et les dates rendues aussitôt. Seul l'auteur de la demande peut l'abandonner.
         */
        post: operations["abandonRentalRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payment/stripe-webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recevoir un événement de Stripe
         * @description Appelée par Stripe seul, jamais par un client. Aucune garde de jeton : l'en-tête `Stripe-Signature` est vérifié sur le corps brut avec `STRIPE_WEBHOOK_SECRET`. Événements lus : `payment_intent.amount_capturable_updated` (empreinte posée) et `checkout.session.expired` (page de paiement expirée).
         */
        post: operations["receiveStripeWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rental-request/{id}/cancellation": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Identifiant de la demande de location (UUID).
                 * @example 9b2f4d6a-1c3e-4f5a-8b7c-0d1e2f3a4b5c
                 */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Annuler une réservation
         * @description Annule une demande qui attend le propriétaire ou une location confirmée, tant qu'elle n'a pas commencé. Le conducteur est remboursé en totalité jusqu'à l'échéance `freeCancellationUntil` incluse, et plus du tout après ; le propriétaire peut annuler à tout moment avant le début, et le conducteur récupère alors tout. Une empreinte non prélevée est toujours levée. Annuler deux fois rend le même effet sans rien refaire.
         */
        post: operations["cancelRental"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Changer d'avatar
         * @description Remplace le pilote choisi comme avatar par le compte porté par le jeton, et lui seul.
         */
        patch: operations["chooseAvatar"];
        trace?: never;
    };
    "/notification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lire ses notifications
         * @description Rend les trente notifications les plus récentes du compte porté par le jeton, et le nombre de ses notifications non lues. La route ne prend aucun identifiant : un compte ne lit que les siennes. L'adresse, le box et les jours sont lus sur l'annonce et la demande au moment de la lecture.
         */
        get: operations["listNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notification/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Marquer ses notifications comme lues
         * @description Marque comme lues toutes les notifications non lues du compte porté par le jeton. Une notification déjà lue garde l'instant de sa première lecture : rejouer la requête ne change rien.
         */
        post: operations["markNotificationsRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notification/push-device": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enregistrer son téléphone
         * @description Rattache le téléphone au compte porté par le jeton, pour qu'il reçoive ses notifications en push. Un téléphone déjà enregistré par un autre compte passe à celui-ci : il n'appartient qu'au dernier compte connecté. L'app l'appelle à chaque session ouverte ; la rejouer ne change rien.
         */
        post: operations["registerPushDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notification/push-device/removal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Oublier un téléphone
         * @description Le téléphone cesse de recevoir des push. Sans authentification : l'app l'appelle en se déconnectant, quand la session est peut-être déjà effacée — et qui connaît le jeton peut déjà pousser vers ce téléphone par Expo. Répond 204 que le jeton soit connu ou non.
         */
        post: operations["forgetPushDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notification/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Marquer une notification comme lue
         * @description Marque comme lue une seule notification du compte porté par le jeton — celle d'une réservation confirmée, une fois fêtée à l'écran. Un identifiant mal formé, inconnu ou appartenant à un autre compte répond 204 comme les autres et ne marque rien : la route ne dit jamais qu'une notification existe.
         */
        post: operations["markNotificationRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lire ses versements
         * @description L'état du compte Stripe du loueur porté par le jeton, et chaque location payée sur ses places : retenue, libérée ou virée. Un compte pas encore validé est relu chez Stripe à chaque lecture.
         */
        get: operations["readPayouts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payout/onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Saisir ses coordonnées bancaires chez Stripe
         * @description Crée au premier appel le compte Stripe Connect Express du loueur, puis rend un lien vers les pages de Stripe où il saisit son identité et son IBAN. Au retour, Stripe renvoie vers `/compte?onglet=versements`.
         */
        post: operations["startPayoutOnboarding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payout/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ouvrir son espace Stripe
         * @description Rend un lien de connexion à l'espace Stripe Express du loueur : son IBAN, ses virements vers sa banque.
         */
        post: operations["openPayoutDashboard"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rental-request/{id}/arrival": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirmer son arrivée
         * @description Le conducteur d'une réservation confirmée dit qu'il est arrivé, à partir du premier instant de la location : l'argent est libéré vers le loueur (D-22). Rejouée, la requête ne change rien.
         */
        post: operations["confirmArrival"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Corps d'erreur rendu par le filtre d'exception NestJS. */
        Error: {
            /** @example 400 */
            statusCode: number;
            /**
             * @description Message en français. Pour une erreur de décodage (400), les échecs sont formatés `chemin: message`.
             * @example Annonce introuvable
             */
            message: string;
        };
        RegisterAccountRequest: {
            /**
             * Format: email
             * @description Adresse e-mail. Les espaces, `@` surnuméraires, apostrophes, guillemets, antislashs et points-virgules sont refusés.
             */
            email: string;
            /** @description Au moins 8 caractères, et une robustesse moyenne ou forte (SPEC-007 RG-02) ; un mot de passe faible est refusé en 400. */
            password: string;
            humanProof: components["schemas"]["HumanProof"];
            /** @description La case « J'accepte les conditions d'utilisation » (SPEC-008). `false` est refusé en 400 ; l'instant de l'acceptation est noté sur le compte. */
            acceptsTerms: boolean;
            avatar: components["schemas"]["Avatar"];
        };
        RegisterAccountResponse: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
        };
        ChangePasswordRequest: {
            currentPassword: string;
            newPassword: string;
        };
        SignInRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        SignInResponse: {
            /** @description Jeton d'accès à porter en `Authorization: Bearer <token>`. */
            token: string;
            /**
             * Format: date-time
             * @description Fin de validité du jeton, en ISO 8601 UTC.
             */
            validUntil: string;
        };
        /** @description Grille tarifaire. Chaque palier est un nombre entier de centimes, ou `null` quand le palier n'existe pas. */
        Pricing: {
            /** @example 1500 */
            dayInCents: number | null;
            /** @example 8000 */
            weekInCents: number | null;
            /** @example 25000 */
            monthInCents: number | null;
        };
        /** @description Une annonce telle qu'elle est rendue par l'API. */
        Listing: {
            /** Format: uuid */
            id: string;
            /** @example 12 rue des Lilas, 75011 Paris */
            address: string;
            /** @example B12 */
            box: string;
            /** @description Références des photos stockées. */
            photos: string[];
            pricing: components["schemas"]["Pricing"];
            availability: {
                /** Format: date-time */
                from: string;
                /** Format: date-time */
                to: string;
            };
            /** @description Les véhicules que la place accepte. Un tableau vide se lit « non déclaré », jamais « n'accepte rien » : les annonces publiées avant cette notion le restent, et une recherche par véhicule ne les écarte pas. `electrique` annonce en outre une borne de recharge. */
            acceptedVehicles: ("velo" | "moto" | "voiture" | "electrique" | "utilitaire")[];
        };
        PublishListingRequest: {
            address: string;
            box: string;
            /** @description Consignes d'accès à la place, remises au locataire une fois la location confirmée. */
            accessDescription: string;
            photos: string[];
            /** @description Au moins un palier. Chaque palier présent est un entier de centimes ; un palier absent n'existe pas. Un palier tarifaire absent doit être **omis** de l'objet : envoyer `null` est refusé en 400 (`Expected number, actual null`), alors que `GET /listing` rend `null` pour un palier vide. Relire une annonce puis la republier telle quelle échoue donc — il faut retirer les clés nulles. */
            pricing: {
                dayInCents?: number;
                weekInCents?: number;
                monthInCents?: number;
            };
            availability: {
                /** Format: date-time */
                from: string;
                /** Format: date-time */
                to: string;
            };
            /** @description Les véhicules que la place accepte. Un tableau vide se lit « non déclaré », jamais « n'accepte rien » : les annonces publiées avant cette notion le restent, et une recherche par véhicule ne les écarte pas. `electrique` annonce en outre une borne de recharge. Facultatif : un client qui ne le déclare pas obtient « non déclaré » plutôt qu'un refus. */
            acceptedVehicles?: ("velo" | "moto" | "voiture" | "electrique" | "utilitaire")[];
        };
        /** @description Nouvelle grille tarifaire. Tous les paliers sont facultatifs, mais la grille résultante doit rester complète au sens du domaine ; un palier omis est effacé. Un palier tarifaire absent doit être **omis** de l'objet : envoyer `null` est refusé en 400 (`Expected number, actual null`), alors que `GET /listing` rend `null` pour un palier vide. Relire une annonce puis la republier telle quelle échoue donc — il faut retirer les clés nulles. */
        UpdateListingPricingRequest: {
            dayInCents?: number;
            weekInCents?: number;
            monthInCents?: number;
        };
        RequestRentalRequest: {
            /** @example 12 rue des Lilas, 75011 Paris */
            address: string;
            /** @example B12 */
            box: string;
            /**
             * Format: date
             * @description Premier jour loué, en jour calendaire `AAAA-MM-JJ`.
             * @example 2026-10-01
             */
            fromDay: string;
            /**
             * Format: date
             * @description Dernier jour loué, en jour calendaire `AAAA-MM-JJ`. La période ne peut pas dépasser 366 jours.
             * @example 2026-10-03
             */
            toDay: string;
        };
        /** @description Une annonce telle que son propriétaire la voit : ce que la lecture publique montre, plus son statut. `accessDescription` reste hors de toute réponse, y compris celle-ci. */
        OwnerListing: {
            /** Format: uuid */
            id: string;
            address: string;
            box: string;
            /**
             * @description Une annonce dépubliée reste visible ici, et nulle part ailleurs.
             * @enum {string}
             */
            status: "ACTIVE" | "UNPUBLISHED";
            photos: string[];
            pricing: components["schemas"]["Pricing"];
            availability: {
                /** Format: date-time */
                from: string;
                /** Format: date-time */
                to: string;
            };
            /** @description Les véhicules que la place accepte. Un tableau vide se lit « non déclaré », jamais « n'accepte rien » : les annonces publiées avant cette notion le restent, et une recherche par véhicule ne les écarte pas. `electrique` annonce en outre une borne de recharge. */
            acceptedVehicles: ("velo" | "moto" | "voiture" | "electrique" | "utilitaire")[];
        };
        /** @description Une demande de location. Ni le locataire ni le propriétaire n'y figurent : les deux routes qui la rendent sont déjà clés sur le compte appelant. */
        RentalRequest: {
            /**
             * Format: uuid
             * @description L'identifiant à passer à `POST /rental-request/{id}/confirmation`.
             */
            id: string;
            /** Format: uuid */
            listingId: string;
            address: string;
            box: string;
            /** Format: date */
            fromDay: string;
            /** Format: date */
            toDay: string;
            /** @description Le montant figé au moment de la demande. */
            priceInCents: number;
            /**
             * @description `AWAITING_PAYMENT` : la page de paiement est ouverte, l'empreinte n'est pas constatée ; la demande retient ses dates mais le propriétaire ne la voit pas. `ABANDONED` : le paiement n'a jamais eu lieu. `PAYMENT_FAILED` : la banque a refusé le prélèvement à la confirmation.
             * @enum {string}
             */
            status: "AWAITING_PAYMENT" | "PENDING" | "CONFIRMED" | "EXPIRED" | "CANCELLED" | "ABANDONED" | "PAYMENT_FAILED";
            /**
             * @description Où en est l'argent du conducteur. `AUTHORIZED` : empreinte posée, rien de prélevé. `CAPTURED` : prélevé à la confirmation. `RELEASE_DUE` / `REFUND_DUE` : l'empreinte est en cours de levée, le remboursement en cours. `NONE` : demande faite avant l'encaissement.
             * @enum {string}
             */
            money: "NONE" | "AUTHORIZED" | "CAPTURED" | "RELEASE_DUE" | "RELEASED" | "REFUND_DUE" | "REFUNDED";
            /** Format: date-time */
            requestedAt: string;
            /** Format: date-time */
            confirmedAt: string | null;
            /**
             * Format: date-time
             * @description Le premier instant de la location, heure de Paris. Une réservation ne s'annule plus à partir de cet instant.
             */
            startsAt: string;
            /**
             * Format: date-time
             * @description L'échéance d'annulation gratuite, figée à la demande : jusqu'à cet instant inclus, le conducteur qui annule une location confirmée est remboursé en totalité.
             */
            freeCancellationUntil: string | null;
            /**
             * Format: date-time
             * @description Tant que la demande attend le loueur (`PENDING`) : l'instant où elle expirera sans réponse, 48 heures (réglables) après l'empreinte, ou après la demande pour celles d'avant l'encaissement. `null` sinon.
             */
            answerBy: string | null;
            /** @description Les consignes d'accès du loueur (digicode, étage, repères). Rendues au seul conducteur d'une réservation `CONFIRMED`, jusqu'à la fin du dernier jour loué ; `null` partout ailleurs, y compris pour le loueur dans `GET /rental-request/received`. */
            accessInstructions: string | null;
            /** @description Pour le seul loueur (`GET /rental-request/received`) : le prix moins la commission figée au moment de la demande. `null` pour le conducteur. */
            ownerShareInCents: number | null;
            /**
             * Format: date-time
             * @description L'instant où le conducteur a confirmé son arrivée (`POST /rental-request/{id}/arrival`), qui libère l'argent vers le loueur.
             */
            arrivedAt: string | null;
        };
        /** @description Trois blocs : les cumuls, l'activité récente, et ce qui demande une attention. */
        Overview: {
            counts: {
                accounts: number;
                suspendedAccounts: number;
                activeListings: number;
                unpublishedListings: number;
                pendingRequests: number;
                confirmedRequests: number;
                cancelledRequests: number;
                confirmedRevenueInCents: number;
            };
            activity: {
                accountsLast24h: number;
                listingsLast24h: number;
                requestsLast24h: number;
                accountsLast7d: number;
                listingsLast7d: number;
                requestsLast7d: number;
            };
            attention: {
                requestsPendingOverADay: number;
                listingsWithoutAnyPrice: number;
                accountsWithoutAnyActivity: number;
            };
        };
        AdminAccount: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            /** Format: date-time */
            registeredAt: string;
            /**
             * Format: date-time
             * @description L'instant où la suspension a été prononcée. `null` est le seul état « non suspendu ».
             */
            suspendedAt: string | null;
            listingCount: number;
            requestCount: number;
        };
        AdminListing: {
            /** Format: uuid */
            id: string;
            address: string;
            box: string;
            /** @description « compte introuvable » si le propriétaire a disparu. */
            ownerEmail: string;
            /** @enum {string} */
            status: "ACTIVE" | "UNPUBLISHED";
            acceptedVehicles: string[];
            pricing: components["schemas"]["Pricing"];
            /** Format: date-time */
            publishedAt: string;
        };
        AdminRentalRequest: {
            /** Format: uuid */
            id: string;
            address: string;
            box: string;
            ownerEmail: string;
            renterEmail: string;
            /** Format: date */
            fromDay: string;
            /** Format: date */
            toDay: string;
            priceInCents: number;
            /** @enum {string} */
            status: "AWAITING_PAYMENT" | "PENDING" | "CONFIRMED" | "EXPIRED" | "CANCELLED" | "ABANDONED" | "PAYMENT_FAILED";
            /** Format: date-time */
            requestedAt: string;
            /** Format: date-time */
            confirmedAt: string | null;
        };
        /** @description Toute action de modération exige un motif. Ce n'est pas une formalité : c'est ce qui permet de répondre, six mois plus tard, à un propriétaire qui demande pourquoi son annonce a disparu. */
        ModerationRequest: {
            reason: string;
        };
        RequestRentalResponse: {
            /**
             * Format: uuid
             * @description L'identifiant de la demande, en attente de paiement.
             */
            id: string;
            /**
             * Format: uri
             * @description La page de paiement Stripe Checkout où le conducteur pose son empreinte. Toujours sur `https://checkout.stripe.com/`.
             */
            checkoutUrl: string;
        };
        CancellationResult: {
            /**
             * @description `RELEASED` : l'empreinte est levée, rien n'avait été prélevé. `REFUNDED` : le prélèvement est remboursé en totalité. `KEPT` : annulation tardive du conducteur, le prélèvement est gardé. `NOTHING_TO_RETURN` : demande faite avant l'encaissement.
             * @enum {string}
             */
            outcome: "RELEASED" | "REFUNDED" | "KEPT" | "NOTHING_TO_RETURN";
        };
        /** @description Défi anti-robot (SPEC-007) : retrouver le nombre `n` ≤ `maxNumber` tel que SHA-256(`salt` + `n`) = `challenge`. Valable 20 minutes. */
        HumanChallenge: {
            /** @enum {string} */
            algorithm: "SHA-256";
            /** @description Condensé SHA-256 hexadécimal. */
            challenge: string;
            /** @description Sel, qui porte son échéance (`?expires=` en secondes Unix). */
            salt: string;
            maxNumber: number;
            /** @description HMAC du condensé, par l'api. */
            signature: string;
        };
        /** @description Le défi recopié, avec le nombre trouvé. Accepté une seule fois. */
        HumanProof: {
            algorithm: string;
            challenge: string;
            salt: string;
            number: number;
            signature: string;
        };
        OwnAccount: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            avatar: components["schemas"]["Avatar"];
        };
        /**
         * @description Le pilote choisi comme avatar : casque bleu signal, jaune marquage, Riviera, bitume ou damier. Les comptes d'avant le choix valent `SIGNAL`.
         * @enum {string}
         */
        Avatar: "SIGNAL" | "MARKING" | "RIVIERA" | "ASPHALT" | "CHECKERED";
        ChooseAvatarRequest: {
            avatar: components["schemas"]["Avatar"];
        };
        /**
         * @description Le moment notifié. Reçue, restée sans réponse et annulée par le conducteur vont au loueur ; acceptée, refusée, expirée, annulée par le loueur et paiement refusé vont au conducteur ; annulée par Bookparking va aux deux. Le virement parti vers son compte Stripe va au loueur.
         * @enum {string}
         */
        NotificationKind: "RENTAL_REQUEST_RECEIVED" | "RENTAL_REQUEST_ACCEPTED" | "RENTAL_REQUEST_DECLINED" | "RENTAL_REQUEST_EXPIRED" | "RENTAL_REQUEST_UNANSWERED" | "RENTAL_CANCELLED_BY_RENTER" | "RENTAL_CANCELLED_BY_OWNER" | "RENTAL_CANCELLED_BY_OPERATOR" | "RENTAL_PAYMENT_FAILED" | "RENTAL_PAYOUT_SENT";
        Notification: {
            /** Format: uuid */
            id: string;
            kind: components["schemas"]["NotificationKind"];
            /**
             * @description Le rôle du destinataire sur la demande : loueur ou conducteur. Décide où le site l'emmène.
             * @enum {string}
             */
            audience: "OWNER" | "RENTER";
            /** Format: date-time */
            createdAt: string;
            /**
             * Format: date-time
             * @description `null` tant que la cloche n'a pas été ouverte.
             */
            readAt: string | null;
            /**
             * Format: uuid
             * @description La demande de location concernée.
             */
            requestId: string;
            address: string;
            box: string;
            /**
             * Format: date
             * @description Premier jour loué, calendrier de Paris.
             */
            fromDay: string;
            /**
             * Format: date
             * @description Dernier jour loué, inclus.
             */
            toDay: string;
        };
        NotificationList: {
            /** @description Toutes les notifications non lues du compte, y compris au-delà des trente rendues. */
            unreadCount: number;
            /** @description Les trente plus récentes, de la plus récente à la plus ancienne. */
            items: components["schemas"]["Notification"][];
        };
        PushDeviceRequest: {
            /** @description Le jeton de push Expo du téléphone, tel que le rend `getExpoPushTokenAsync`. */
            token: string;
        };
        PayoutLine: {
            /** Format: uuid */
            requestId: string;
            address: string;
            box: string;
            /** Format: date */
            fromDay: string;
            /** Format: date */
            toDay: string;
            /** @description Ce que le conducteur a payé. */
            priceInCents: number;
            /** @description Ce que le loueur reçoit : le prix moins la commission figée à la demande. */
            amountInCents: number;
            /**
             * @description HELD : retenu jusqu'à l'arrivée du conducteur ou 24 h après le début. AWAITING_ACCOUNT : libéré, en attente des coordonnées bancaires. SENDING : libéré, viré au prochain passage. SENT : viré.
             * @enum {string}
             */
            status: "HELD" | "AWAITING_ACCOUNT" | "SENDING" | "SENT";
            /** Format: date-time */
            releaseAt: string;
            /** Format: date-time */
            transferredAt: string | null;
        };
        PayoutSummary: {
            /**
             * @description MISSING : aucune coordonnée bancaire. INCOMPLETE : inscription Stripe commencée ou en vérification. READY : Stripe accepte les virements.
             * @enum {string}
             */
            accountStatus: "MISSING" | "INCOMPLETE" | "READY";
            /** @description La commission en vigueur pour les nouvelles demandes. */
            feePercent: number;
            upcomingInCents: number;
            sentInCents: number;
            payouts: components["schemas"]["PayoutLine"][];
        };
        StripeLink: {
            /**
             * Format: uri
             * @description Une page de Stripe, valable quelques minutes.
             */
            url: string;
        };
        RequestPasswordResetRequest: {
            email: string;
        };
        ResetPasswordRequest: {
            token: string;
            newPassword: string;
        };
    };
    responses: {
        /** @description Jeton d'accès absent, mal formé ou invalide. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Erreur inattendue. */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Le compte n'appartient pas à l'administration du site. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /**
         * @description Identifiant de l'annonce (UUID), tel que rendu par `GET /listing`.
         * @example 3f1a9c0e-9c1e-4c5e-8a2b-1f2d3e4a5b6c
         */
        ListingId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readOwnAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Le compte connecté. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnAccount"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Le jeton désigne un compte qui n'existe plus. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    registerAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterAccountRequest"];
            };
        };
        responses: {
            /** @description Compte créé. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterAccountResponse"];
                };
            };
            /** @description Corps de requête invalide : adresse e-mail mal formée ou trop longue (254 caractères au maximum), mot de passe de moins de 8 caractères ou trop faible, preuve anti-robot absente, fausse, expirée ou déjà servie, conditions d'utilisation non acceptées, avatar absent ou hors des cinq pilotes. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Adresse e-mail déjà utilisée. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    issueHumanChallenge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Défi émis. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HumanChallenge"];
                };
            };
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Mot de passe changé. Aucun corps de réponse. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Corps de requête invalide, ou nouveau mot de passe trop faible (moins de 8 caractères). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Mot de passe actuel incorrect. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    requestPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestPasswordResetRequest"];
            };
        };
        responses: {
            /** @description Demande reçue. Aucun corps de réponse, que l'adresse ait un compte ou non. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Corps de requête invalide. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Mot de passe remplacé. Aucun corps de réponse. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Corps de requête invalide, lien inconnu, expiré ou déjà utilisé, ou nouveau mot de passe trop faible. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    signIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignInRequest"];
            };
        };
        responses: {
            /** @description Session ouverte. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignInResponse"];
                };
            };
            /** @description Corps de requête invalide. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Identifiants incorrects. Le message est le même pour une adresse inconnue et pour un mot de passe faux. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listListings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Liste des annonces actives, éventuellement vide. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Listing"][];
                };
            };
            /** @description La liste des annonces est indisponible. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    publishListing: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishListingRequest"];
            };
        };
        responses: {
            /** @description Annonce publiée. Aucun corps de réponse. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Corps de requête invalide, période de disponibilité déjà passée, grille tarifaire incomplète, ou type de véhicule inconnu. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Cette place a déjà une annonce active. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalServerError"];
            /** @description Le stockage des photos a échoué. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listOwnerListings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description La liste, éventuellement vide. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnerListing"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getListing: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Identifiant de l'annonce (UUID), tel que rendu par `GET /listing`.
                 * @example 3f1a9c0e-9c1e-4c5e-8a2b-1f2d3e4a5b6c
                 */
                id: components["parameters"]["ListingId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description L'annonce demandée. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Listing"];
                };
            };
            /** @description Annonce introuvable — identifiant inconnu ou mal formé. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    unpublishListing: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Identifiant de l'annonce (UUID), tel que rendu par `GET /listing`.
                 * @example 3f1a9c0e-9c1e-4c5e-8a2b-1f2d3e4a5b6c
                 */
                id: components["parameters"]["ListingId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Annonce dépubliée, ou rien à dépublier. Aucun corps de réponse. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            /** @description L'annonce appartient à un autre compte. Le refus n'est pas caché derrière un `404` : `GET /listing/{id}` est public de toute façon. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    updateListingPricing: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Identifiant de l'annonce (UUID), tel que rendu par `GET /listing`.
                 * @example 3f1a9c0e-9c1e-4c5e-8a2b-1f2d3e4a5b6c
                 */
                id: components["parameters"]["ListingId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateListingPricingRequest"];
            };
        };
        responses: {
            /** @description L'annonce, avec sa nouvelle grille tarifaire. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Listing"];
                };
            };
            /** @description Corps de requête invalide (un prix n'est pas un nombre entier de centimes), ou grille tarifaire incomplète. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description L'annonce appartient à un autre compte. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Aucune annonce active pour cette place — identifiant inconnu ou mal formé compris. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    listMyRentalRequests: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description La liste, éventuellement vide. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RentalRequest"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    requestRental: {
        parameters: {
            query?: never;
            header: {
                /** @description L'identifiant d'intention, un UUID choisi par le client pour une place et une période. Renvoyé à l'identique, il rend la demande déjà créée — même identifiant, même page de paiement — au lieu d'en créer une seconde, et la réponse porte alors `Idempotent-Replayed: true`. Il est propre au compte qui l'envoie. */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestRentalRequest"];
            };
        };
        responses: {
            /** @description Demande enregistrée, en attente de paiement. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestRentalResponse"];
                };
            };
            /** @description Corps de requête invalide, ou en-tête `Idempotency-Key` absent ou qui n'est pas un UUID. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Une demande sous cet identifiant d'intention est en cours de création : réessayer dans un instant. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description La demande est bien formée mais le domaine la refuse. Messages possibles : « Les dates demandées sont invalides », « La période demandée dépasse la durée maximale de 366 jours », « Ces dates sont déjà louées », « Cette place n'a aucune annonce publiée », « Aucun tarif ne couvre la période demandée ». « Cet identifiant de demande a déjà servi pour une autre place ou une autre période ». */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalServerError"];
            /** @description Stripe ne répond pas : la demande est abandonnée et ses dates rendues. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listReceivedRentalRequests: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description La liste, éventuellement vide. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RentalRequest"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    confirmRentalRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Identifiant de la demande de location (UUID).
                 * @example 9b2f4d6a-1c3e-4f5a-8b7c-0d1e2f3a4b5c
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Demande confirmée. Aucun corps de réponse. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            /** @description Demande inexistante, identifiant mal formé, ou demande appartenant à un autre compte. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description La demande a expiré et ne peut plus être confirmée. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalServerError"];
            /** @description Stripe ne répond pas : rien n'est prélevé ni confirmé, la confirmation peut être rejouée. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    confirmAdminAccess: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ce compte administre le site. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    readAdminOverview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description La liste. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overview"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listAdminAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description La liste. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminAccount"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listAdminListings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description La liste. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminListing"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listAdminRentalRequests: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description La liste. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminRentalRequest"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    adminUnpublishListing: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModerationRequest"];
            };
        };
        responses: {
            /** @description Fait. L'action est inscrite au journal de modération. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Motif absent ou trop court. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Cible inexistante, ou déjà dans l'état demandé. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    adminSuspendAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModerationRequest"];
            };
        };
        responses: {
            /** @description Fait. L'action est inscrite au journal de modération. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Motif absent ou trop court. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Cible inexistante, ou déjà dans l'état demandé. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    adminLiftAccountSuspension: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModerationRequest"];
            };
        };
        responses: {
            /** @description Fait. L'action est inscrite au journal de modération. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Motif absent ou trop court. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Cible inexistante, ou déjà dans l'état demandé. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    adminCancelRentalRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModerationRequest"];
            };
        };
        responses: {
            /** @description Fait. L'action est inscrite au journal de modération. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Motif absent ou trop court. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Cible inexistante, ou déjà dans l'état demandé. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    abandonRentalRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Identifiant de la demande de location (UUID).
                 * @example 9b2f4d6a-1c3e-4f5a-8b7c-0d1e2f3a4b5c
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Demande abandonnée, ou déjà abandonnée. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            /** @description Demande inexistante, identifiant mal formé, ou demande d'un autre compte. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description L'empreinte est déjà posée : la demande attend le propriétaire. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    receiveStripeWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Événement accusé, qu'il ait changé une demande ou non. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Signature absente ou invalide. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cancelRental: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Identifiant de la demande de location (UUID).
                 * @example 9b2f4d6a-1c3e-4f5a-8b7c-0d1e2f3a4b5c
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Réservation annulée. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancellationResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Demande inexistante, identifiant mal formé, ou demande que ce compte ne peut ni voir ni annuler. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description La location a commencé, ou la demande n'est ni en attente du propriétaire ni confirmée. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    chooseAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChooseAvatarRequest"];
            };
        };
        responses: {
            /** @description Avatar changé. Aucun corps de réponse. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Avatar absent ou hors des cinq pilotes. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Le jeton désigne un compte qui n'existe plus. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    listNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Les notifications du compte. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    markNotificationsRead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Notifications marquées comme lues. Aucun corps de réponse. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    registerPushDevice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushDeviceRequest"];
            };
        };
        responses: {
            /** @description Téléphone enregistré. Aucun corps de réponse. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Jeton absent, ou qui n'est pas un jeton de push Expo. La valeur soumise n'est jamais recopiée. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    forgetPushDevice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushDeviceRequest"];
            };
        };
        responses: {
            /** @description Téléphone oublié, ou inconnu. Aucun corps de réponse. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Jeton absent, ou qui n'est pas un jeton de push Expo. La valeur soumise n'est jamais recopiée. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    markNotificationRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aucun corps de réponse. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    readPayouts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Les versements du compte. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PayoutSummary"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    startPayoutOnboarding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Le lien vers Stripe. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StripeLink"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
            /** @description Stripe ne répond pas. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    openPayoutDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Le lien vers Stripe. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StripeLink"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Stripe n'a pas encore validé le compte. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalServerError"];
            /** @description Stripe ne répond pas. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    confirmArrival: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Arrivée enregistrée. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            /** @description Demande inconnue, mal nommée ou d'un autre compte. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Réservation pas encore confirmée, ou location pas encore commencée. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
}
