/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inscrire un compte
         * @description Crée un compte à partir d'une adresse e-mail et d'un mot de passe. Route publique.
         */
        post: operations["registerAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Changer son mot de passe
         * @description Change le mot de passe du compte porté par le jeton. Le mot de passe actuel est exigé.
         */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ouvrir une session
         * @description Vérifie les identifiants et rend un jeton d'accès.
         *
         *     Les essais infructueux sont ralentis : le délai dépend du couple (compte, origine IP) et croît avec les échecs récents. Une origine que la requête ne nomme pas retombe sur une clé commune. Le ralentissement n'a pas de code de statut propre — un essai ralenti répond simplement plus tard, toujours `401` s'il échoue, pour ne pas distinguer une adresse inconnue d'un mot de passe faux.
         */
        post: operations["signIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/listing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lister les annonces actives
         * @description Rend toutes les annonces actives. Route publique, sans pagination ni filtre à ce jour.
         */
        get: operations["listListings"];
        put?: never;
        /**
         * Publier une annonce
         * @description Publie une annonce pour une place — identifiée par le couple (adresse, box) — au nom du compte porté par le jeton.
         *
         *     La grille tarifaire doit être complète au sens du domaine : au moins un palier, et pas de palier contradictoire.
         */
        post: operations["publishListing"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/listing/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lister ses propres annonces
         * @description Rend les annonces du compte appelant, **quel que soit leur statut** — c'est la seule route qui montre une annonce dépubliée. Déclarée avant `/listing/{id}` côté serveur, sans quoi « mine » serait décodé comme un identifiant.
         */
        get: operations["listOwnerListings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/listing/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Identifiant de l'annonce (UUID), tel que rendu par `GET /listing`.
                 * @example 3f1a9c0e-9c1e-4c5e-8a2b-1f2d3e4a5b6c
                 */
                id: components["parameters"]["ListingId"];
            };
            cookie?: never;
        };
        /**
         * Lire une annonce
         * @description Rend une annonce par son identifiant. Route publique : une annonce est lisible par tout le monde.
         *
         *     Un identifiant mal formé répond `404`, comme un identifiant inconnu.
         */
        get: operations["getListing"];
        put?: never;
        post?: never;
        /**
         * Dépublier une annonce
         * @description Dépublie l'annonce du compte porté par le jeton.
         *
         *     L'opération est idempotente : un identifiant mal formé, inconnu, ou une annonce déjà dépubliée répondent tous `204`. Cette route n'est donc pas un oracle d'existence.
         */
        delete: operations["unpublishListing"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/listing/{id}/pricing": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Identifiant de l'annonce (UUID), tel que rendu par `GET /listing`.
                 * @example 3f1a9c0e-9c1e-4c5e-8a2b-1f2d3e4a5b6c
                 */
                id: components["parameters"]["ListingId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Changer la grille tarifaire d'une annonce
         * @description Remplace la grille tarifaire de l'annonce active. Un palier absent du corps est effacé : la grille envoyée remplace la précédente en entier.
         */
        patch: operations["updateListingPricing"];
        trace?: never;
    };
    "/rental-request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lister les demandes que l'on a faites
         * @description Rend les demandes de location faites par le compte appelant, en tant que locataire.
         */
        get: operations["listMyRentalRequests"];
        put?: never;
        /**
         * Demander une location
         * @description Demande la location d'une place — identifiée par le couple (adresse, box) — sur une période de jours calendaires, au nom du compte porté par le jeton.
         *
         *     Une demande non confirmée expire au bout du délai configuré par `RENTAL_REQUEST_EXPIRY_IN_HOURS` (48 heures par défaut).
         */
        post: operations["requestRental"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rental-request/received": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lister les demandes reçues sur ses places
         * @description Rend les demandes faites sur les annonces du compte appelant, en tant que propriétaire. C'est **la seule route qui rend l'identifiant d'une demande** à un client, et donc la seule qui rende `POST /rental-request/{id}/confirmation` atteignable.
         */
        get: operations["listReceivedRentalRequests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rental-request/{id}/confirmation": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Identifiant de la demande de location (UUID).
                 * @example 9b2f4d6a-1c3e-4f5a-8b7c-0d1e2f3a4b5c
                 */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirmer une demande de location
         * @description Confirme une demande de location. Seul le propriétaire de la place peut confirmer.
         *
         *     Un identifiant mal formé, une demande inconnue et une demande appartenant à quelqu'un d'autre répondent toutes `404`, avec le même message.
         */
        post: operations["confirmRentalRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Corps d'erreur rendu par le filtre d'exception NestJS. */
        Error: {
            /** @example 400 */
            statusCode: number;
            /**
             * @description Message en français. Pour une erreur de décodage (400), les échecs sont formatés `chemin: message`.
             * @example Annonce introuvable
             */
            message: string;
        };
        RegisterAccountRequest: {
            /**
             * Format: email
             * @description Adresse e-mail. Les espaces, `@` surnuméraires, apostrophes, guillemets, antislashs et points-virgules sont refusés.
             */
            email: string;
            password: string;
        };
        RegisterAccountResponse: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
        };
        ChangePasswordRequest: {
            currentPassword: string;
            newPassword: string;
        };
        SignInRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        SignInResponse: {
            /** @description Jeton d'accès à porter en `Authorization: Bearer <token>`. */
            token: string;
            /**
             * Format: date-time
             * @description Fin de validité du jeton, en ISO 8601 UTC.
             */
            validUntil: string;
        };
        /** @description Grille tarifaire. Chaque palier est un nombre entier de centimes, ou `null` quand le palier n'existe pas. */
        Pricing: {
            /** @example 1500 */
            dayInCents: number | null;
            /** @example 8000 */
            weekInCents: number | null;
            /** @example 25000 */
            monthInCents: number | null;
        };
        /** @description Une annonce telle qu'elle est rendue par l'API. */
        Listing: {
            /** Format: uuid */
            id: string;
            /** @example 12 rue des Lilas, 75011 Paris */
            address: string;
            /** @example B12 */
            box: string;
            /** @description Références des photos stockées. */
            photos: string[];
            pricing: components["schemas"]["Pricing"];
            availability: {
                /** Format: date-time */
                from: string;
                /** Format: date-time */
                to: string;
            };
            /** @description Les véhicules que la place accepte. Un tableau vide se lit « non déclaré », jamais « n'accepte rien » : les annonces publiées avant cette notion le restent, et une recherche par véhicule ne les écarte pas. `electrique` annonce en outre une borne de recharge. */
            acceptedVehicles: ("velo" | "moto" | "voiture" | "electrique" | "utilitaire")[];
        };
        PublishListingRequest: {
            address: string;
            box: string;
            /** @description Consignes d'accès à la place, remises au locataire une fois la location confirmée. */
            accessDescription: string;
            photos: string[];
            /** @description Au moins un palier. Chaque palier présent est un entier de centimes ; un palier absent n'existe pas. Un palier tarifaire absent doit être **omis** de l'objet : envoyer `null` est refusé en 400 (`Expected number, actual null`), alors que `GET /listing` rend `null` pour un palier vide. Relire une annonce puis la republier telle quelle échoue donc — il faut retirer les clés nulles. */
            pricing: {
                dayInCents?: number;
                weekInCents?: number;
                monthInCents?: number;
            };
            availability: {
                /** Format: date-time */
                from: string;
                /** Format: date-time */
                to: string;
            };
            /** @description Les véhicules que la place accepte. Un tableau vide se lit « non déclaré », jamais « n'accepte rien » : les annonces publiées avant cette notion le restent, et une recherche par véhicule ne les écarte pas. `electrique` annonce en outre une borne de recharge. Facultatif : un client qui ne le déclare pas obtient « non déclaré » plutôt qu'un refus. */
            acceptedVehicles?: ("velo" | "moto" | "voiture" | "electrique" | "utilitaire")[];
        };
        /** @description Nouvelle grille tarifaire. Tous les paliers sont facultatifs, mais la grille résultante doit rester complète au sens du domaine ; un palier omis est effacé. Un palier tarifaire absent doit être **omis** de l'objet : envoyer `null` est refusé en 400 (`Expected number, actual null`), alors que `GET /listing` rend `null` pour un palier vide. Relire une annonce puis la republier telle quelle échoue donc — il faut retirer les clés nulles. */
        UpdateListingPricingRequest: {
            dayInCents?: number;
            weekInCents?: number;
            monthInCents?: number;
        };
        RequestRentalRequest: {
            /** @example 12 rue des Lilas, 75011 Paris */
            address: string;
            /** @example B12 */
            box: string;
            /**
             * Format: date
             * @description Premier jour loué, en jour calendaire `AAAA-MM-JJ`.
             * @example 2026-10-01
             */
            fromDay: string;
            /**
             * Format: date
             * @description Dernier jour loué, en jour calendaire `AAAA-MM-JJ`. La période ne peut pas dépasser 366 jours.
             * @example 2026-10-03
             */
            toDay: string;
        };
        /** @description Une annonce telle que son propriétaire la voit : ce que la lecture publique montre, plus son statut. `accessDescription` reste hors de toute réponse, y compris celle-ci. */
        OwnerListing: {
            /** Format: uuid */
            id: string;
            address: string;
            box: string;
            /**
             * @description Une annonce dépubliée reste visible ici, et nulle part ailleurs.
             * @enum {string}
             */
            status: "ACTIVE" | "UNPUBLISHED";
            photos: string[];
            pricing: components["schemas"]["Pricing"];
            availability: {
                /** Format: date-time */
                from: string;
                /** Format: date-time */
                to: string;
            };
            /** @description Les véhicules que la place accepte. Un tableau vide se lit « non déclaré », jamais « n'accepte rien » : les annonces publiées avant cette notion le restent, et une recherche par véhicule ne les écarte pas. `electrique` annonce en outre une borne de recharge. */
            acceptedVehicles: ("velo" | "moto" | "voiture" | "electrique" | "utilitaire")[];
        };
        /** @description Une demande de location. Ni le locataire ni le propriétaire n'y figurent : les deux routes qui la rendent sont déjà clés sur le compte appelant. */
        RentalRequest: {
            /**
             * Format: uuid
             * @description L'identifiant à passer à `POST /rental-request/{id}/confirmation`.
             */
            id: string;
            /** Format: uuid */
            listingId: string;
            address: string;
            box: string;
            /** Format: date */
            fromDay: string;
            /** Format: date */
            toDay: string;
            /** @description Le montant figé au moment de la demande. */
            priceInCents: number;
            /** @enum {string} */
            status: "PENDING" | "CONFIRMED" | "EXPIRED";
            /** Format: date-time */
            requestedAt: string;
            /** Format: date-time */
            confirmedAt: string | null;
        };
    };
    responses: {
        /** @description Jeton d'accès absent, mal formé ou invalide. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Erreur inattendue. */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /**
         * @description Identifiant de l'annonce (UUID), tel que rendu par `GET /listing`.
         * @example 3f1a9c0e-9c1e-4c5e-8a2b-1f2d3e4a5b6c
         */
        ListingId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    registerAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterAccountRequest"];
            };
        };
        responses: {
            /** @description Compte créé. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterAccountResponse"];
                };
            };
            /** @description Corps de requête invalide : adresse e-mail mal formée ou trop longue (254 caractères au maximum), mot de passe de moins de 8 caractères. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Adresse e-mail déjà utilisée. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Mot de passe changé. Aucun corps de réponse. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Corps de requête invalide, ou nouveau mot de passe trop faible (moins de 8 caractères). */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Mot de passe actuel incorrect. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    signIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignInRequest"];
            };
        };
        responses: {
            /** @description Session ouverte. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignInResponse"];
                };
            };
            /** @description Corps de requête invalide. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Identifiants incorrects. Le message est le même pour une adresse inconnue et pour un mot de passe faux. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listListings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Liste des annonces actives, éventuellement vide. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Listing"][];
                };
            };
            /** @description La liste des annonces est indisponible. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    publishListing: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishListingRequest"];
            };
        };
        responses: {
            /** @description Annonce publiée. Aucun corps de réponse. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Corps de requête invalide, période de disponibilité déjà passée, grille tarifaire incomplète, ou type de véhicule inconnu. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Cette place a déjà une annonce active. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalServerError"];
            /** @description Le stockage des photos a échoué. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listOwnerListings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description La liste, éventuellement vide. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnerListing"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getListing: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Identifiant de l'annonce (UUID), tel que rendu par `GET /listing`.
                 * @example 3f1a9c0e-9c1e-4c5e-8a2b-1f2d3e4a5b6c
                 */
                id: components["parameters"]["ListingId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description L'annonce demandée. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Listing"];
                };
            };
            /** @description Annonce introuvable — identifiant inconnu ou mal formé. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    unpublishListing: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Identifiant de l'annonce (UUID), tel que rendu par `GET /listing`.
                 * @example 3f1a9c0e-9c1e-4c5e-8a2b-1f2d3e4a5b6c
                 */
                id: components["parameters"]["ListingId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Annonce dépubliée, ou rien à dépublier. Aucun corps de réponse. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            /** @description L'annonce appartient à un autre compte. Le refus n'est pas caché derrière un `404` : `GET /listing/{id}` est public de toute façon. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    updateListingPricing: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Identifiant de l'annonce (UUID), tel que rendu par `GET /listing`.
                 * @example 3f1a9c0e-9c1e-4c5e-8a2b-1f2d3e4a5b6c
                 */
                id: components["parameters"]["ListingId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateListingPricingRequest"];
            };
        };
        responses: {
            /** @description L'annonce, avec sa nouvelle grille tarifaire. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Listing"];
                };
            };
            /** @description Corps de requête invalide (un prix n'est pas un nombre entier de centimes), ou grille tarifaire incomplète. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description L'annonce appartient à un autre compte. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Aucune annonce active pour cette place — identifiant inconnu ou mal formé compris. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    listMyRentalRequests: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description La liste, éventuellement vide. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RentalRequest"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    requestRental: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestRentalRequest"];
            };
        };
        responses: {
            /** @description Demande enregistrée. Aucun corps de réponse. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Corps de requête invalide. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description La demande est bien formée mais le domaine la refuse. Messages possibles : « Les dates demandées sont invalides », « La période demandée dépasse la durée maximale de 366 jours », « Ces dates sont déjà louées », « Cette place n'a aucune annonce publiée », « Aucun tarif ne couvre la période demandée ». */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    listReceivedRentalRequests: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description La liste, éventuellement vide. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RentalRequest"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    confirmRentalRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Identifiant de la demande de location (UUID).
                 * @example 9b2f4d6a-1c3e-4f5a-8b7c-0d1e2f3a4b5c
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Demande confirmée. Aucun corps de réponse. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            /** @description Demande inexistante, identifiant mal formé, ou demande appartenant à un autre compte. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description La demande a expiré et ne peut plus être confirmée. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
}
